### ISSUE TITLE
Error on Linux: File .projectroot not found

### ISSUE THREAD

**Issue by StephGbzh** [DaniilAlpha/minisound#12]
After a few months of inactivity, I reopened a flutter project and upgraded the dependencies, including minisound, which resulted in theses changes:

minisound 1.3.8 > 1.4.1
minisound_ffi 1.3.8 > 1.5.0
minisound_platform_interface 1.1.4 > 1.5.0
minisound_web 1.3.8 > 1.5.0

When trying to run the app on my Linux system (Ubuntu 24.04), I now get this error and no app running:

```
Launching lib/main.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/minisound_ffi/src/CMakeLists.txt:39 (message):
  File .projectroot not found within 2 levels up from
  /home/user/project/linux/flutter/ephemeral/.plugin_symlinks/minisound_ffi/src
2

Error: Unable to generate build files

Exited (1).
```

I rollbacked the versions in `pubspec.yaml`

from:

```
  minisound: ^1.3.7
```

to:

```
  minisound: 1.3.8
  minisound_ffi: 1.3.8
  minisound_platform_interface: 1.1.4
  minisound_web: 1.3.8
```

and with these modifications, it works again.

Can you check what is wrong with this `.projectroot` code ?

**Comment by DaniilAlpha** [comment]
Unfortunately, i was (and will be for a while) busy with other projects, and was not able to release a proper new version, so it will stay in this state for several weeks. I messed up versions on pub.dev, and there is the only way to fix this - set dependencies to the exact versions in your pubspec:
```
minisound: ^1.4.1
minisound_web: 1.4.1
minisound_ffi: 1.4.0
minisound_platform_interface: 1.2.0
```
I will attempt to fix this ASAP.

**Comment by StephGbzh** [comment]
Replacing the overrides for all versions of minisound* with just `minisound: ^1.6.0` works like a charm.

Thank you !

Congrats on the big refactoring !
