### ISSUE TITLE
v2.0.2 Build Fails on Windows

### ISSUE THREAD

**Issue by Mr4Mike4** [DaniilAlpha/minisound#13]
Minisound example is not build on Windows 10.

Error: `command line  error D8004: '/W' requires an argument`

I have the same error in my app. How do I fix the error?
 
<details>

<summary>Build log</summary>

[   +3 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] K:\Flutter\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe --disable-dart-dev K:\Flutter\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server_aot.dart.snapshot --sdk-root K:\Flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true --output-dill j:\Temp\TempUser\Temp\flutter_tools.ce12e0b1\flutter_tool.a4b17380\app.dill --packages K:\FlutterProjects\workspace_temp\minisound\minisound\example\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill --source file:///K:/FlutterProjects/workspace_temp/minisound/minisound/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///K:/FlutterProjects/workspace_temp/minisound/minisound/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +19 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +99 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "f550b056",
               "installDate": "2022-01-04T19:20:36Z",
               "installationName": "VisualStudio/17.11.5+35327.3",
               "installationPath": "l:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.11.35327.3",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "l:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Мощная интегрированная среда разработки, бесплатная для студентов, участников проектов с открытым кодом и отдельных пользователей.",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelId": "VisualStudio.17.Release",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.11#17.11.5",
               "resolvedInstallationPath": "L:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2024-11-04T18:47:11.7655969Z",
               "catalog": {
                 "buildBranch": "d17.11",
                 "buildVersion": "17.11.35327.3",
                 "id": "VisualStudio/17.11.5+35327.3",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.11.5",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.11.5+35327.3",
                 "requiredEngineVersion": "3.11.2180.21897"
               },
               "properties": {
                 "campaignId": "1",
                 "channelManifestId": "VisualStudio.17.Release/17.11.5+35327.3",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
Building Windows application...
[  +19 ms] <- compile package:example/main.dart
[   +1 ms] executing: l:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows -B K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64 -G Visual Studio 17 2022 -A x64 -DFLUTTER_TARGET_PLATFORM=windows-x64
[  +97 ms] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
[  +20 ms] -- Configuring done (0.0s)
[  +69 ms] -- Generating done (0.1s)
[   +4 ms] -- Build files have been written to: K:/FlutterProjects/workspace_temp/minisound/minisound/example/build/windows/x64
[   +9 ms] executing: l:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64 --config Debug --target INSTALL --verbose
[  +68 ms] Change Dir: 'K:/FlutterProjects/workspace_temp/minisound/minisound/example/build/windows/x64'
[        ] Run Build Command(s): "l:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" INSTALL.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
[  +80 ms] MSBuild version 17.11.9+a69bbaaf5 for .NET Framework
[  +44 ms] Build started 05.11.2024 0:57:03.
[ +205 ms] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\INSTALL.vcxproj" on node 1 (default targets).
[        ] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\INSTALL.vcxproj" (1) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[   +4 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[        ]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[   +8 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +26 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[   +1 ms] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ZERO_CHECK.vcxproj" (default targets).
[  +58 ms] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\INSTALL.vcxproj" (1) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
[        ] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (3) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\example.vcxproj" (4) on node 1 (default targets).
[        ] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\example.vcxproj" (4) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_assemble.vcxproj" (5) on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[  +21 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[        ]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +3 ms] CustomBuild:
[        ]   "The build of 'K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\CMakeFiles\09bfd01e338ebf42e15d2789e859680c\flutter_assemble.rule' depends on 'K:\FLUTTERPROJECTS\WORKSPACE_TEMP\MINISOUND\MINISOUND\EXAMPLE\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of 'K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\CMakeFiles\c743fd70860d892f35439cc3cf10ca44\flutter_windows.dll.rule'. The items cannot be built in parallel."
[+6542 ms]   Generating K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_windows.dll, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_export.h, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_windows.h, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_messenger.h, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_plugin_registrar.h, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/flutter_texture_registrar.h, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc, K:/FlutterProjects/workspace_temp/minisound/minisound/example/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[        ]   [ +120 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ]   [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [  +76 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ]   [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ]   [  +18 ms] Initializing file store
[        ]   [  +11 ms] Done initializing file store
[        ]   [  +38 ms] Skipping target: gen_localizations
[        ]   [   +6 ms] Skipping target: gen_dart_plugin_registrant
[        ]   [+2560 ms] Skipping target: unpack_windows
[        ]   [ +419 ms] Skipping target: kernel_snapshot_program
[        ]   [   +4 ms] Skipping target: native_assets
[        ]   [   +1 ms] Skipping target: kernel_snapshot_native_assets
[        ]   [        ] Skipping target: kernel_snapshot
[        ]   [   +3 ms] invalidated build due to missing files: K:\FlutterProjects\workspace_temp\minisound\minisound\example\DOES_NOT_EXIST_RERUN_FOR_WILDCARD938104623
[        ]   [ +435 ms] debug_bundle_windows-x64_assets: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: K:\FlutterProjects\workspace_temp\minisound\minisound\example\DOES_NOT_EXIST_RERUN_FOR_WILDCARD938104623}
[        ]   [ +115 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +9 ms]   [+1947 ms] shaderc command: [K:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr, --sl=K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\flutter_assets\shaders/ink_sparkle.frag, --spirv=K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=K:\Flutter\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=K:\Flutter\flutter\packages\flutter\lib\src\material\shaders, --include=K:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
[ +597 ms]   [ +597 ms] debug_bundle_windows-x64_assets: Complete
[ +203 ms]   [ +203 ms] Persisting file store
[   +6 ms]   [   +6 ms] Done persisting file store
[   +5 ms]   [   +5 ms] build succeeded.
[   +8 ms]   [   +7 ms] "flutter assemble" took 6┬а481ms.
[   +3 ms]   [   +4 ms] Running 1 shutdown hook
[        ]   [        ] Shutdown hooks complete
[   +2 ms]   [   +2 ms] exiting with code 0
[  +57 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
[   +1 ms] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_assemble.vcxproj" (default targets).
[  +19 ms] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\example.vcxproj" (4) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_wrapper_app.vcxproj" (6) on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_app.dir\Debug\flutter_.3CA52AF7.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[        ]   Touching "flutter_wrapper_app.dir\Debug\flutter_.3CA52AF7.tlog\unsuccessfulbuild".
[   +4 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +41 ms] ClCompile:
[        ]   All outputs are up-to-date.
[  +17 ms] Lib:
[        ]   All outputs are up-to-date.
[   +1 ms]   flutter_wrapper_app.vcxproj -> K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\Debug\flutter_wrapper_app.lib
[  +15 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_app.dir\Debug\flutter_.3CA52AF7.tlog\unsuccessfulbuild".
[        ]   Touching "flutter_wrapper_app.dir\Debug\flutter_.3CA52AF7.tlog\flutter_wrapper_app.lastbuildstate".
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_wrapper_app.vcxproj" (default targets).
[   +5 ms] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "example.dir\Debug\example.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[        ]   Touching "example.dir\Debug\example.tlog\unsuccessfulbuild".
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +12 ms] ClCompile:
[        ]   l:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\CL.exe /c /IK:\FlutterProjects\workspace_temp\minisound\minisound\example\windows /IK:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral /IK:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\cpp_client_wrapper\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D "FLUTTER_VERSION=\"1.0.0\"" /D FLUTTER_VERSION_MAJOR=1 /D FLUTTER_VERSION_MINOR=0 /D FLUTTER_VERSION_PATCH=0 /D FLUTTER_VERSION_BUILD=0 /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"example.dir\Debug\\" /Fd"example.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\generated_plugin_registrant.cc K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\runner\flutter_window.cpp
[ +244 ms]   generated_plugin_registrant.cc
[ +209 ms]   flutter_window.cpp
[ +672 ms]   Generating Code...
[  +68 ms] ResourceCompile:
[        ]   All outputs are up-to-date.
[  +25 ms] Link:
[        ]   l:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\Debug\example.exe" /INCREMENTAL /ILK:"example.dir\Debug\example.ilk" /NOLOGO ..\flutter\Debug\flutter_wrapper_app.lib dwmapi.lib K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /manifestinput:K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\runner\runner.exe.manifest /DEBUG /PDB:"K:/FlutterProjects/workspace_temp/minisound/minisound/example/build/windows/x64/runner/Debug/example.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"K:/FlutterProjects/workspace_temp/minisound/minisound/example/build/windows/x64/runner/Debug/example.lib" /MACHINE:X64  /machine:x64 example.dir\Debug\Runner.res
[        ]   example.dir\Debug\flutter_window.obj
[        ]   example.dir\Debug\main.obj
[        ]   example.dir\Debug\utils.obj
[        ]   example.dir\Debug\win32_window.obj
[        ]   example.dir\Debug\generated_plugin_registrant.obj
[ +322 ms]   example.vcxproj -> K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\Debug\example.exe
[   +7 ms] FinalizeBuildStatus:
[        ]   Deleting file "example.dir\Debug\example.tlog\unsuccessfulbuild".
[        ]   Touching "example.dir\Debug\example.tlog\example.lastbuildstate".
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\runner\example.vcxproj" (default targets).
[  +22 ms] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (3) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_wrapper_plugin.vcxproj" (7) on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[        ] InitializeBuildStatus:
[        ]   Creating "flutter_wrapper_plugin.dir\Debug\flutter_.345D2880.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[        ]   Touching "flutter_wrapper_plugin.dir\Debug\flutter_.345D2880.tlog\unsuccessfulbuild".
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[   +6 ms] ClCompile:
[        ]   All outputs are up-to-date.
[   +2 ms] Lib:
[        ]   All outputs are up-to-date.
[        ]   flutter_wrapper_plugin.vcxproj -> K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\Debug\flutter_wrapper_plugin.lib
[   +9 ms] FinalizeBuildStatus:
[        ]   Deleting file "flutter_wrapper_plugin.dir\Debug\flutter_.345D2880.tlog\unsuccessfulbuild".
[        ]   Touching "flutter_wrapper_plugin.dir\Debug\flutter_.345D2880.tlog\flutter_wrapper_plugin.lastbuildstate".
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\flutter\flutter_wrapper_plugin.vcxproj" (default targets).
[  +18 ms] Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (3) is building "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\plugins\minisound_ffi\shared\minisound_ffi.vcxproj" (8) on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
[        ] InitializeBuildStatus:
[        ]   Touching "minisound_ffi.dir\Debug\minisound_ffi.tlog\unsuccessfulbuild".
[   +1 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[   +9 ms] ClCompile:
[        ]   l:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\CL.exe /c /Zi /nologo /Wall /WX- /diagnostics:column /Od /Ob0 /D _WINDLL /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D DART_SHARED_LIB /D MILO_DEFAULT_LVL=MILO_LVL_NONE /D ENGINE_MILO_LVL=MILO_LVL_NONE /D SOUND_MILO_LVL=MILO_LVL_NONE /D RECORDER_MILO_LVL=MILO_LVL_NONE /D MA_ENABLE_ONLY_SPECIFIC_BACKENDS /D MA_NO_RESOURCE_MANAGER /D MA_ENABLE_WASAPI /D MA_ENABLE_PULSEAUDIO /D MA_ENABLE_JACK /D MA_ENABLE_ALSA /D MA_ENABLE_OPENSL /D MA_ENABLE_COREAUDIO /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /D minisound_ffi_EXPORTS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"minisound_ffi.dir\Debug\\" /Fd"minisound_ffi.dir\Debug\vc143.pdb" /external:W4 /Gd /TC /errorReport:queue  -W -Wextra -Wformat -Wno-unused-function -O3 K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\external\miniaudio\src\miniaudio.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\engine.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\milo.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\recorder\recorder.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\recorder\recorder_buffer.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\recorder\recording.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound_data\encoded_sound_data.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound_data\noise_sound_data.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound_data\pulse_sound_data.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound_data\silence_data_source.c K:\FlutterProjects\workspace_temp\minisound\minisound\example\windows\flutter\ephemeral\.plugin_symlinks\minisound_ffi\src\src\sound_data\waveform_sound_data.c
[ +166 ms] cl : command line  error D8004: '/W' requires an argument [K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\plugins\minisound_ffi\shared\minisound_ffi.vcxproj]
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\plugins\minisound_ffi\shared\minisound_ffi.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\INSTALL.vcxproj" (default targets) -- FAILED.
[   +2 ms] Build FAILED.
[        ] "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\INSTALL.vcxproj" (default target) (1) ->
[        ] "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\plugins\minisound_ffi\shared\minisound_ffi.vcxproj" (default target) (8) ->
[        ] (ClCompile target) -> 
[        ]   cl : command line  error D8004: '/W' requires an argument [K:\FlutterProjects\workspace_temp\minisound\minisound\example\build\windows\x64\plugins\minisound_ffi\shared\minisound_ffi.vcxproj]
[        ]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:09.69
[  +14 ms] Error: Build process failed.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

[   +9 ms] "flutter run" took 12 134ms.
[   +1 ms] Running 2 shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
</details>

<details>

<summary>Doctor output</summary>

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.5011], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2024.1)
[√] Android Studio (version 2024.2)
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] VS Code (version 1.90.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
</details>

**Comment by DaniilAlpha** [comment]
It looks like i've made a mistake assuming that msvc has the same compiler arguments as normal compilers do. Please check if this has been fixed after upgrading the packages (minisound_ffi should become 2.0.3).

**Comment by Mr4Mike4** [comment]
The fix works. Thank you.
